### ISSUE TITLE
Better explanations for initial questions

### ISSUE THREAD

**Issue by coderamm** [Atrone/MindMateGPT-V3#1]
The website asks the user about their MBTI type, their relationship status, their relationship with their childhood and their work. It's unclear what these inputs are used for, if at all. The website must make it clear why these questions are being asked, and what bearing they have on the behaviour of the AI during conversations.

**Comment by Atrone** [comment]
@coderamm How's this?
![image](https://github.com/Atrone/MindMateGPT-V3/assets/35811311/f598ad22-81d7-4f16-929f-a58db5634a3f)
